#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

vdb-config --interactive

module load sratoolkit

fastq-dump --outdir /projectnb/bf528/users/saxophone/data_p2/raw_data -I --split-files /projectnb/bf528/users/saxophone/data_p2/raw_data/P0_1.sra

echo "Job finished: $(date +%F)"
