#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

module load samtools bowtie2 boost tophat

tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf \
--segment-length=20 --segment-mismatches=1 --no-novel-juncs \
-o /projectnb2/bf528/users/saxophone/data_p2/P0_1_tophat -p 16 \
/project/bf528/project_2/reference/mm9 \
/projectnb2/bf528/users/saxophone/data_p2/raw_data/P0_1_1.fastq \
/projectnb2/bf528/users/saxophone/data_p2/raw_data/P0_1_2.fastq

echo "Job finished: $(date +%F)"
